# TinyOS Cargo Configuration
# This overrides any global ~/.cargo/config.toml settings

[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
runner = ["sh", "-c", "qemu-system-aarch64 -M raspi4b -kernel $1 -serial stdio -display none", "--"]
rustflags = ["-C", "link-arg=-Tlinker.ld"]

# Explicitly disable test harness to prevent "can't find crate for test" errors
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[profile.test]
panic = "abort"

# Disable test targets completely
[target.'cfg(target_arch = "aarch64")']
runner = ["echo", "Tests disabled for no_std target"]

# Note: build-std is available if needed for advanced no-std scenarios
# Uncomment the following lines if you need to rebuild core/alloc from source:
# [unstable]
# build-std = ["core", "alloc"]
# build-std-features = ["compiler-builtins-mem"]

# Override any global target settings for this workspace
[env]
CARGO_BUILD_TARGET = "aarch64-unknown-none"
# Force no test compilation
CARGO_CFG_TEST = "0"
