#!/bin/bash

# Interactive test script for TinyOS with System Health Check
echo "TinyOS Interactive Command Test"
echo "==============================="
echo ""
echo "Your professional OS kernel is now running and waiting for commands!"
echo ""
echo "🔧 SYSTEM COMMANDS:"
echo "  h or H - Show comprehensive help menu"
echo "  t or T - Show current precise system time"
echo "  s or S - Show detailed system information"
echo "  c or C - 🏥 Run SYSTEM HEALTH CHECK (The main feature!)"
echo ""
echo "⚡ HARDWARE CONTROL:"
echo "  1      - Turn LED ON manually"
echo "  0      - Turn LED OFF manually"
echo "  l or L - Toggle LED state"
echo ""
echo "📊 DIAGNOSTICS:"
echo "  m or M - Show memory information"
echo "  d or D - Show hardware diagnostics"
echo ""
echo "✨ HIGHLIGHTS:"
echo "  • No more automatic LED spam!"
echo "  • Professional command interface"
echo "  • System Health Check with comprehensive testing"
echo "  • LED control is now on-demand"
echo "  • All commands show precise timestamps"
echo ""
echo "🚀 RECOMMENDED TEST SEQUENCE:"
echo "  1. Type 'h' to see the full help menu"
echo "  2. Type 'c' to run the System Health Check"
echo "  3. Type '1' to turn LED on, then '0' to turn it off"
echo "  4. Type 's' to see detailed system info"
echo ""
echo "To exit QEMU: Press Ctrl+A, then X"
echo "=================================="
