name: Test QEMU Installation Options

on:
  workflow_dispatch:

jobs:
  test-qemu-options:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test different QEMU installation methods
      run: |
        echo "=== Testing QEMU Installation Options ==="
        
        # Option 1: Check what's available via apt
        echo "1. Ubuntu 24.04 QEMU packages:"
        apt-cache policy qemu-system-aarch64
        
        # Option 2: Try snap installation
        echo "2. Snap QEMU packages:"
        snap find qemu || echo "Snap search failed"
        
        # Option 3: Check if we can use a PPA
        echo "3. Checking for QEMU PPAs:"
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        
        # Option 4: Download pre-built binaries
        echo "4. Check QEMU download options:"
        wget -q -O - https://download.qemu.org/ | grep -i "download" | head -5 || echo "Website check failed"
        
        # Install default version and check capabilities
        echo "5. Installing default QEMU and checking capabilities:"
        sudo apt-get install -y qemu-system-aarch64
        
        echo "QEMU version:"
        qemu-system-aarch64 --version
        
        echo "Available machine types:"
        qemu-system-aarch64 -machine help | grep -E "(raspi|virt)" | head -10
        
        echo "Available CPUs:"
        qemu-system-aarch64 -cpu help | grep -E "(cortex|arm)" | head -10
